### ISSUE TITLE
about code

### ISSUE THREAD

**Issue by cenchaojun** [ZNan-Chen/diffCOD#1]
Thank you for your great work!
I was wondering if you plan to release your code anytime soon.

**Comment by ZNan-Chen** [comment]
Thanks for your interest in this project, I'm currently busy with another project, so I'll organize the code and publish it in a month.

**Comment by 111sadas** [comment]
Thank you for your great work!
Your paper and related work are great, but you haven't published the code yet. Can I see your code now?
